import "./globals.css";
import { ConvexProvider, ConvexReactClient } from "convex/react";
import React from "react";
import type { Metadata } from "next";
// Convex
const convex = new ConvexReactClient(
  "https://savory-dotterel-250.convex.cloud/"
);
import localFont from 'next/font/local';
import {ChakraProvider} from "@chakra-ui/react";

// Causing havoc >:D

const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});

const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};
export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    return (
          <html lang="en">
            <React.StrictMode>
    return (
          <html lang="en">
            <React.StrictMode>
        <ConvexProvider client={convex}>
          <body className={`${geistSans.variable} ${geistMono.variable}`}>
                  {children}
                </body>
              </ConvexProvider>
                  {children}
                </body>
              </ConvexProvider>
      </React.StrictMode>
    </html>
    );
}
